"""
Bundles the modular CSS source files into a single src/css/main.css.

Edit the source files in src/css/base/ and src/css/components/, then run
this script to regenerate main.css. Do not hand-edit main.css directly —
it's a generated file.

Why bundle instead of using @import: browsers must download and parse a
stylesheet before they can discover its @import rules, adding a serial
round-trip before the imported files even start fetching. A single
concatenated file loads in one request with no discovery delay, while
still letting the project be authored as small, focused per-component
files.

Run from the project root:
    python scripts/build_css.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSS_DIR = ROOT / "src" / "css"
OUTPUT = CSS_DIR / "main.css"

# Order matters: tokens/reset/typography/layout first, then components
# (components are order-independent among themselves).
BASE_FILES = [
    "base/variables.css",
    "base/reset.css",
    "base/typography.css",
    "base/layout.css",
]

COMPONENT_FILES = [
    "components/buttons.css",
    "components/header.css",
    "components/footer.css",
    "components/media-placeholder.css",
    "components/cards.css",
    "components/cta-banner.css",
    "components/badges.css",
    "components/forms.css",
    "components/breadcrumb.css",
    "components/process-steps.css",
    "components/checklist.css",
]

BANNER = """/*
  RainTree Immigration — main stylesheet (GENERATED FILE).

  Do not edit this file directly — it's bundled from the modular source
  files in src/css/base/ and src/css/components/ by scripts/build_css.py.
  Edit those files, then run:
      python scripts/build_css.py
*/
"""


def main():
    parts = [BANNER]
    for rel_path in BASE_FILES + COMPONENT_FILES:
        content = (CSS_DIR / rel_path).read_text(encoding="utf-8").strip()
        parts.append(f"\n/* ===== {rel_path} ===== */\n\n{content}\n")

    OUTPUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Bundled {len(BASE_FILES) + len(COMPONENT_FILES)} files into {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
